#!/usr/bin/env python

'''
Created on 15/06/2015

@author: andrea
'''

"""
    Execution:
        predecirModelo_UpCrossSelling dataFile modelName predictionOutputFile
        
    Command line arguments:
        dataFile (sys.argv[1]): String that indicates the complete path of the file where the data to be classified resides.       
        modelName (sys.argv[2]): String that indicates the name of the file where the model was previously saved.
        predictionOutputFile (sys.argv[3]): String that indicates the complete plath of the file where the result of the prediction is going to be saved.
"""

import sys
import os

from iMathModelosPredictivos.core.modelUpCrossSelling import ModelUpCrossSelling
from iMathModelosPredictivos.common.constants import CONS
from iMathModelosPredictivos.common.util.masMovilError import MasMovilError
from iMathModelosPredictivos.scripts_UpCrossSelling.help import showExtendedHelp
from iMathModelosPredictivos.scripts_UpCrossSelling.help import showShortHelp

CONS = CONS()

try:
    
    # Check if help is required
    if len(sys.argv) == 2:
        if sys.argv[1] == '--help':
            print ""
            showExtendedHelp('predictModel')
            print ""
            quit()
    
    # Check the number of parameters
    if len(sys.argv) != 4:
        raise MasMovilError("Numero incorrecto de parametros")
    
    dataFile = sys.argv[1]
    modelName = sys.argv[2]
    predictionOutputFile = sys.argv[3]
    
    # Check if the data file exists
    if os.path.isfile(dataFile) is False:
        raise MasMovilError("El fichero " + dataFile + " no existe");
    
    # Check if the file that contains the model exists
    model_path = os.path.join(CONS.MODEL_FILE_LOCATION + modelName + ".txt")
    if os.path.isfile(model_path) is False:
        raise MasMovilError("El modelo " +   modelName  + " no ha sido previamente creado");
    
    print ""
    model = ModelUpCrossSelling(model_path);
    model.predictModel(dataFile, predictionOutputFile);
    print ""
    
except MasMovilError as e:
    print ""
    print "[iMathResearch] Error: " , e.value
    if e.value == "Numero incorrecto de parametros":
        showShortHelp('predictModel')    
    print ""