#!/usr/bin/env python

import sys
import os

from iMathModelosPredictivos.core.modelPredictPosition import ModelPredictUserPosition
from iMathModelosPredictivos.core.SignalPrediction.Data.constants import CONS

from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

CONS = CONS()

try:
                      
    # Check the number of parameters
    '''if len(sys.argv) != 4:
        print "Numero de parametros incorrectos"
    
    dataFile = sys.argv[1]
    classifierType = sys.argv[2]
    modelName = sys.argv[3]'''

    dataFile = '/home/izubizarreta/Documentos/Documentos/Comercial/Sensovida/Prediccion/Registers155Training.csv'
    classifierType = 'RandomForestClassifier'
    modelName = 'ModeloPrediccion'
    
    # Check if the classifier exists
    if classifierType == 'DecisionTreeClassifier':
        classifier = DecisionTreeClassifier
    elif classifierType == "SVC":
        classifier = SVC
    elif classifierType == "RandomForestClassifier":
        classifier = RandomForestClassifier
    print ""
    model = ModelPredictUserPosition(dataFile, classifier);
    model.saveModel(CONS.MODEL_FILE_LOCATION + modelName + '.txt');
    print "Modelo creado y guardado"
    
except:
    print ""
    print 'Error. Numero incorrecto de parametros'
    print ""